// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://trybqrktjibalolvsvej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRyeWJxcmt0amliYWxvbHZzdmVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU1ODU4ODIsImV4cCI6MjA1MTE2MTg4Mn0.69wE-pxSWLlkGsgNztaGzatByVpd62ieOAQ9qF0V_4A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);